Public Class ClsMain
    Public Class PostingGroupSalesTaxParty
        Public Const Composition As String = "Composition"
        Public Const Registered As String = "Registered"
        Public Const Unregistered As String = "Unregistered"
    End Class
    Public Class PostingGroupSalesTaxItem
        Public Const GST0 As String = "GST 0%"
        Public Const GST12 As String = "GST 12%"
        Public Const GST18 As String = "GST 18%"
        Public Const GST28 As String = "GST 28%"
        Public Const GST5 As String = "GST 5%"
    End Class
    Public Class SubGroupType
        Public Const Customer As String = "Customer"
        Public Const PurchaseAgent As String = "Purchase Agent"
        Public Const RevenuePoint As String = "Revenue Point"
        Public Const SalesAgent As String = "Sales Agent"
        Public Const SalesRepresentative As String = "Sales Representative"
        Public Const Supplier As String = "Supplier"
        Public Const Transporter As String = "Transporter"
        Public Const LedgerAccount As String = "Ledger Account"
    End Class
    Public Class AccountGroupNature
        Public Const Sales As String = "Sales"
        Public Const Purchase As String = "Purchase"
        Public Const Bank As String = "Bank"
        Public Const Cash As String = "Cash"
        Public Const Customer As String = "Customer"
        Public Const Supplier As String = "Supplier"
        Public Const Expenses As String = "Expenses"
        Public Const Income As String = "Income"
        Public Const Tax As String = "Tax"
        Public Const Others As String = "Others"
    End Class
    Public Class VoucherTypeNature
        Public Const Sale As String = "Sale"
        Public Const Purchase As String = "Purchase"
        Public Const DebitNote As String = "Debit Note"
        Public Const CreditNote As String = "Credit Note"
        Public Const Payment As String = "Payment"
        Public Const Receipt As String = "Receipt"
        Public Const Journal As String = "Journal"
    End Class
    Public Class State
        Public Const JAMMUANDKASHMIR As String = "JAMMU AND KASHMIR"
        Public Const HIMACHALPRADESH As String = "HIMACHAL PRADESH"
        Public Const PUNJAB As String = "PUNJAB"
        Public Const CHANDIGARH As String = "CHANDIGARH"
        Public Const UTTARAKHAND As String = "UTTARAKHAND"
        Public Const HARYANA As String = "HARYANA"
        Public Const DELHI As String = "DELHI"
        Public Const RAJASTHAN As String = "RAJASTHAN"
        Public Const UTTARPRADESH As String = "UTTAR PRADESH"
        Public Const BIHAR As String = "BIHAR"
        Public Const SIKKIM As String = "SIKKIM"
        Public Const ARUNACHALPRADESH As String = "ARUNACHAL PRADESH"
        Public Const NAGALAND As String = "NAGALAND"
        Public Const MANIPUR As String = "MANIPUR"
        Public Const MIZORAM As String = "MIZORAM"
        Public Const TRIPURA As String = "TRIPURA"
        Public Const MEGHLAYA As String = "MEGHLAYA"
        Public Const ASSAM As String = "ASSAM"
        Public Const WESTBENGAL As String = "WEST BENGAL"
        Public Const JHARKHAND As String = "JHARKHAND"
        Public Const ODISHA As String = "ODISHA"
        Public Const CHATTISGARH As String = "CHATTISGARH"
        Public Const MADHYAPRADESH As String = "MADHYA PRADESH"
        Public Const GUJARAT As String = "GUJARAT"
        Public Const DAMANANDDIU As String = "DAMAN AND DIU"
        Public Const DADRAANDNAGARHAVELI As String = "DADRA AND NAGAR HAVELI"
        Public Const MAHARASHTRA As String = "MAHARASHTRA"
        Public Const ANDHRAPRADESHBEFOREDIVISION As String = "ANDHRA PRADESH(BEFORE DIVISION)"
        Public Const KARNATAKA As String = "KARNATAKA"
        Public Const GOA As String = "GOA"
        Public Const LAKSHWADEEP As String = "LAKSHWADEEP"
        Public Const KERALA As String = "KERALA"
        Public Const TAMILNADU As String = "TAMIL NADU"
        Public Const PUDUCHERRY As String = "PUDUCHERRY"
        Public Const ANDAMANANDNICOBARISLANDS As String = "ANDAMAN AND NICOBAR ISLANDS"
        Public Const TELANGANA As String = "TELANGANA"
        Public Const ANDHRAPRADESHNew As String = "ANDHRA PRADESH (NEW)"
    End Class
End Class
